# site settings
title: Harold Affo,PMP, PMI-ACP
subtitle: 
email: affoharold@gmail.com
description: My Portfolio
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Frederick
state: MD
zip_code: 21704
country: United States of America
phone: (240) 898 8391

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# contact form settings
form_url: https://formspree.io/affoharold@gmail.com # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url:
facebook_url:
github_url: https://github.com/haffo
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/harold-affo-pmp-pmi-acp-95381638/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/afrold

# build settings
markdown: kramdown

sass:
  style: compressed
